### ISSUE TITLE
About the new code you gave

### ISSUE THREAD

**Issue by Liujin21** [BruceW91/CVSE#9]
Hello, I have always appreciated your work, but recently I discovered that the results of your new code are different from the results of the old code. What have you changed? Can I continue to use your old code?

**Comment by BruceW91** [comment]
Hi, recently we found that our old version of code is problematic and so we release the new code to correct it.  Actually I don't suggest you to use the old code since it's problematic when it loads the data at inference stage.  If you have more questions, you can contact me by e-mail (haoranwang@tju.edu.cn).

**Comment by Liujin21** [comment]
Ok thank you very much for your reply
